version: '3'
services:
  app:
    image: mical150/carpoolmate
    container_name: carpoolmate
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    networks:
      - backend
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge
