services:
  app:
    image: mical150/carpoolmate
    container_name: carpoolmate
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    networks:
      - backend
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  redis-data:
