name: CI/CD


on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 자바 설치
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Gradle 캐싱
        uses: actions/cache@v2
        with:
         path: ~/.gradle/caches
         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
         restore-keys: |
           ${{ runner.os }}-gradle-

      - name: Resource 폴더 생성
        run: mkdir -p ./src/main/resources/

      - name: properties 생성
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties

      - name: 테스트 없는 Build
        run: ./gradlew build -x test

      - name: 아티팩트 업로드
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: app-artifact
          path: ./build/libs/*.jar

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app-artifact

      - name: List the downloaded files
        run: |
          ls -al ./  # 다운로드된 파일이 있는 디렉토리 확인

      - name: Create app-artifact directory
        run: |
          mkdir -p app-artifact  # 디렉토리 생성

      - name: Move JAR file to app-artifact
        run: |
          mv *.jar app-artifact/  # JAR 파일을 app-artifact 디렉토리로 이동

      - name: Docker 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker 이미지 빌드
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.PROJECT_NAME }} .

      - name: DockerHub 푸쉬
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.PROJECT_NAME }}

#      - name: 메인서버 배포
#        uses: appleboy/ssh-action@v0.1.10
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: |
#            sudo docker kill ${{ secrets.PROJECT_NAME }} || true
#            sudo docker rm -f ${{ secrets.PROJECT_NAME }} || true
#            sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/${{ secrets.PROJECT_NAME }} || true
#            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.PROJECT_NAME }}
#            sudo docker run -d -p 80:8080 --name ${{ secrets.PROJECT_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.PROJECT_NAME }}

      - name: 현재 작업 디렉토리 출력
        run: echo $GITHUB_WORKSPACE
      - name: 확인 docker-compose.yml 파일 위치
        run: |
          echo "path: $(pwd)"
          echo "docker-compose.yml contains: $(ls -l docker-compose.yml)"
      - name: 확인 docker-compose.yml 파일 존재
        run: |
          echo "path: $(pwd)"
          ls -l /home/runner/work/MATE_BackEnd/MATE_BackEnd/docker-compose.yml

     # docker-compose.yml 파일 서버로 전달
      - name: Send docker-compose.yml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: /home/runner/work/MATE_BackEnd/MATE_BackEnd/docker-compose.yml
          target: /home/ubuntu/

      # 서버에서 Docker Compose 명령어 실행
      - name: Run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu
            sudo docker compose down --remove-orphans
            sudo docker compose pull
            sudo docker compose up -d

