name: CI

on:
  push:
    branches:
      - deploytest
  pull_request:
    branches:
      - deploytest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Run tests
        run: |
          ./gradlew test  # 프로젝트에 맞는 테스트 명령어 사용
