name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create resources folder (if not exists)
        run: mkdir -p ./src/main/resources/
        
      - name: Create application.properties
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties

      # - name: Verify application.properties content
      #   run: cat ./src/main/resources/application.properties

      - name: Build project without running tests
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test --info
        
      - name: Build project with logs
        run: ./gradlew build --stacktrace --info

      - name: Verify JAR file
        run: ls build/libs/

      - name: Copy JAR file to EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/my-ec2-key.pem
          chmod 600 ~/.ssh/my-ec2-key.pem
          ssh-keyscan -H 3.38.95.46 >> ~/.ssh/known_hosts
          scp -i ~/.ssh/my-ec2-key.pem build/libs/myapp.jar ubuntu@3.38.95.46:/home/ubuntu/
