name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Create resources folder (if not exists)
        run: mkdir -p ./src/main/resources/
        
      - name: Create application.properties
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties

      - name: Verify application.properties content
        run: cat ./src/main/resources/application.properties

      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build project without running tests
        run: |
          ./gradlew build -x test
